---

etc_hosts_routing: |
  10.101.1.71     o3-master

src_addr_whitelist:
  - 37.123.179.154/32 # HQ
  - 213.89.24.38/32   # Carl's Home
  - 10.101.66.0/24
  - 10.101.96.0/24
  - 82.96.2.60/32     # Sto Office QA
  - 10.110.132.0/24

yarn_nodemanager_resource_memory_mb: 12288
yarn_scheduler_maximum_allocation_mb: 12288

hadoop_admins:
  - mblomdahl
  - cbackstrom

airflow_port: 8090
airflow_admins:
  - mblomdahl
  - cbackstrom
  - fdesing

jupyter_admins:
  - mblomdahl
  - cbackstrom
  - fdesing

...
