---

- name: provision common baseline
  hosts: all
  become: yes
  become_user: root
  roles:
    - common

- name: configure hdfs, yarn and spark
  hosts: all
  become: yes
  become_user: hadoop
  roles:
    - hadoop

- name: provision hive
  hosts: master-nodes
  become: yes
  become_user: root
  roles:
    - hive

- name: provision airflow
  hosts: master-nodes
  become: yes
  become_user: root
  roles:
    - airflow

- name: provision jupyter
  hosts: master-nodes
  become: yes
  become_user: root
  roles:
    - jupyter

...
